name: Build and Test
on:
  push:
    branches: [master, dev]
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Maven with Docker Profile
        run: mvn clean install -Pdocker -DskipTests -B
      - name: Docker Compose Build
        run: docker-compose build

  unit-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: core
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start MYSQL Server
        run: sudo /etc/init.d/mysql start
      - name: Modify MySQL Connection Variables
        run: |
          sed -i "s/'@'localhost'/'@'%'/g" ${GITHUB_WORKSPACE}/src/main/resources/database/moduleSchemas.sql
          sed -i 's/TEST_MYSQL_PORT=3306/TEST_MYSQL_PORT=8888/g' ${GITHUB_WORKSPACE}/.env
      - name: Run Unit Tests
        run: mvn test -B -e -X

  integration-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: core
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start MYSQL Server
        run: sudo /etc/init.d/mysql start
      - name: Modify MySQL Connection Variables
        run: |
          sed -i "s/'@'localhost'/'@'%'/g" ${GITHUB_WORKSPACE}/src/main/resources/database/moduleSchemas.sql
          sed -i 's/TEST_MYSQL_PORT=3306/TEST_MYSQL_PORT=8888/g' ${GITHUB_WORKSPACE}/.env
      - name: Prepare Intergration Tests
        run: |
          sudo apt-get -y install libargon2-0
          mvn -Pdocker validate
      - name: Run Intergration Tests
        run: |
          mvn verify -DskipUTs=true -DmongoDocker -B

  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
